<?php

/* Default options */
const DEFAULT_CONTROLLER = "Nota";
const DEFAULT_ACTION = "list";

const CONTROLLERS_FOLDER="controller";
const MODELS_FOLDER = "model";
const REPOSITORIES_FOLDER=MODELS_FOLDER.DIRECTORY_SEPARATOR."repository";
const ENTITY_FOLDER=MODELS_FOLDER.DIRECTORY_SEPARATOR."entity";
const SERVICIO_FOLDER=MODELS_FOLDER.DIRECTORY_SEPARATOR."servicio";

const INCLUDES_FOLDER="includes";
const TRAITS_FOLDER=MODELS_FOLDER.DIRECTORY_SEPARATOR."traits";

const CONFIG_FOLDER ="config";
const FILES_FOLDER ="files";

